name: Deploy Setup

on:
  push:
    branches:
      - feature-gu

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Change to infra directory
        run: cd infra

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Stack Construct"
          title: "Terraform Plan"
          branch: main
          body: This PR plans the deploy and stack construction
          draft: false
