name: Deploy Setup

on:
  push:
    branches:
      - feature-gu
jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: |
          if terraform fmt -check; then
            echo "Terraform files are correctly formatted."
          else
            echo "Terraform files are incorrectly formatted. Please run 'terraform fmt' to format them."
            exit 1
          fi

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Stack Construct"
          title: "Terraform Plan"
          branch: main
          body: This PR plans the deploy and stack construction
          draft: false
